id: I6E3121E2
legacy_id: P000687
ocr_import_info:
  bdrc_scan_id: W8684
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:16:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:24:12.162367+00:00'
last_modified: 2022-09-04 11:26:02.681556
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8684
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8684
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཤཱཀྱ་རིན་ཆེན།
  author: འབྲུག་རྗེ་མཁན་པོ ༠༩་ཤཱཀྱ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.6615727613088688
  ocr_word_median_confidence_index: 0.6899999976158142
quality: null
bases:
  I4371:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4371
      total_pages: 660
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4371.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6355740165801294
    legacy_id: v007
  I4366:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4366
      total_pages: 836
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4366.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6692608066968122
    legacy_id: v002
  I4367:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4367
      total_pages: 654
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4367.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6853933235271761
    legacy_id: v003
  I4370:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4370
      total_pages: 544
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4370.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6285473846660642
    legacy_id: v006
  I4369:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4369
      total_pages: 590
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4369.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6703142234722751
    legacy_id: v005
  I4368:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4368
      total_pages: 478
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4368.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6784305969249882
    legacy_id: v004
  I4372:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4372
      total_pages: 514
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4372.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6824913043474083
    legacy_id: v008
  I4365:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4365
      total_pages: 612
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4365.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6359771224247531
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
