id: I6E3121E2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:20:01+00:00'
last_modified: '2022-06-07T12:39:56.675081+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8684
  title: གསུང་འབུམ། ཤཱཀྱ་རིན་ཆེན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8C68:
      image_group_id: I4365
      title: ''
      total_pages: 612
      order: 1
      base_file: 8C68.txt
    D25A:
      image_group_id: I4366
      title: ''
      total_pages: 836
      order: 2
      base_file: D25A.txt
    9D06:
      image_group_id: I4367
      title: ''
      total_pages: 654
      order: 3
      base_file: 9D06.txt
    B096:
      image_group_id: I4368
      title: ''
      total_pages: 478
      order: 4
      base_file: B096.txt
    DF29:
      image_group_id: I4369
      title: ''
      total_pages: 590
      order: 5
      base_file: DF29.txt
    EC2A:
      image_group_id: I4370
      title: ''
      total_pages: 544
      order: 6
      base_file: EC2A.txt
    0ABB:
      image_group_id: I4371
      title: ''
      total_pages: 660
      order: 7
      base_file: 0ABB.txt
    '8710':
      image_group_id: I4372
      title: ''
      total_pages: 514
      order: 8
      base_file: 8710.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
